version: "3"
services:
  vite-react-template:
    image: ghcr.io/example/vite-react-template:latest
    ports:
      - 8080:80
    restart: always

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30
    restart: always
